name: datalocal
description: "Flutter dependency to save data via local saved with state, easy to use and fast."
repository: "https://github.com/lamun-my-id/datalocal.git"
version: 1.0.6
# test    : dart pub publish --dry-run
# deploy  : dart pub publish 

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  pointycastle: ^3.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true